fund_methods:
  - Transfer
  - Debit
  - Credit
  - Charge
  - Capture
  - Payout
  - Refund
  - Reversal
  - Settle

external_clients:
  - bankClient
  - walletClient
  - ledgerClient
  - partnerClient
  - paymentGateway
